# Generated by Django 5.2 on 2025-04-09 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blood_stock', '0001_initial'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('last_donation_date', models.DateField(auto_now_add=True)),
                ('virus_test_result', models.BooleanField(default=False)),
                ('expiration_date', models.DateField()),
                ('status', models.CharField(default='1', max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('blood_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blood_stock.bloodstockprofile')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=14, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.city')),
            ],
        ),
    ]
