# Generated by Django 5.2 on 2025-04-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donationrequest_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
