# Generated by Django 5.2 on 2025-04-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_alter_donationrequest_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
