# Generated by Django 5.2 on 2025-04-09 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_donationrequest_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='city',
        ),
    ]
