# Generated by Django 5.2 on 2025-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_remove_donationrequest_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2024-03-01 00:00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
